### ISSUE TITLE
[BUG] aliasing component names result in broken `get!` behaviour

### ISSUE THREAD

**Issue by wraitii** [dojoengine/dojo#780] opened 2023-08-16 14:56 UTC
**Describe the bug**
The `get!` macro behaves incorrectly when passed an aliased component type name.

**To Reproduce**
Something along the lines of 
```
#[derive(Component)]
struct A {
    #[key]
    id: felt252,
    value: felt252,
}


#[derive(Component)]
struct B {
    #[key]
    id: felt252,
    value: u32, 
}

get!(ctx.world, (5), A).value

// elsewhere
use B as A;
get!(ctx.world, (5), A).value
```

**Expected behavior**
The macro should use the component name (I think that's a thing?)

**Comment by ponderingdemocritus** [comment] 2023-11-20 16:48
@wraitii do you know if this is still an issue?

**Comment by wraitii** [comment] 2023-11-20 17:23
> @wraitii do you know if this is still an issue?

Haven't checked recently, but if the macro is still simple text replacement it probably is ?

**Comment by glihm** [comment] 2024-02-14 03:11
Yes, the issue is still here.

Due to a limitation on how inline macro works, the only context the macro has is a `SyntaxGroup`, which can almost be reduced to text processing. And macro evolution will limit this more, as it will be a `TokenStream`, pure text.

For this reason, without a module context, we can't retrieve the `use` statement, were we may get the alias. The ideal would have been the compiler to replace before the macro is called.

I will close this as it can't be addressed right now. Will re-open if the macro context evolves and allow such thing. :+1:

**Closed by glihm** 2024-02-14 03:11 UTC
Labels: bug
