### ISSUE TITLE
Generate component protobuf interfaces

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#6] opened 2023-01-11 15:32 UTC
During compilation, we can output protobuf definitions for component structs which can be used by the server / apibara to provide strictly typed event interfaces.

**Comment by fracek** [comment] 2023-01-11 16:08
I believe codegen is the way to go at first. In theory it's possible to use reflection on the server to "type" the API based on the contract ABI, in practice it's 20x the effort. The benefit of the second approach is that users can use the same server binary across projects, which in turns means ryogoku (the dojo as a service project) can more easily create api servers on the fly.

**Comment by milancermak** [comment] 2023-01-11 16:37
Is there a way to do event versioning? 

One issue we ran into when building Realms is dealing with historical events and contract upgrades. Let's say you want to display combat history on the client. Every combat result is represented by a `CombatOutcome` event. The problem is we had to update the structure of the event (e.g. unit composition, adding/removing a field, ...) with a lot of the updates to the combat logic. We settled for a pragmatic approach of doing `CombatOutcome1`, `CombatOutcome2` whenever there was an update of the event.

**Comment by fracek** [comment] 2023-01-11 17:01
grpc/protobuf is good at that because all fields are optional and devs can add or delete fields from the struct and the parser still parses them.

**Comment by ponderingdemocritus** [comment] 2023-03-31 03:18
this can be tackled now we have the manifest

**Comment by ponderingdemocritus** [comment] 2023-04-03 12:35
@fracek do you want to tackle this?

**Comment by ponderingdemocritus** [comment] 2023-05-24 22:33
closing this as implementation path has changed

**Closed by ponderingdemocritus** 2023-05-24 22:33 UTC
Labels: Duration: 3 days, Difficulty: intermediate
