### ISSUE TITLE
[BUG]: Dojo inline macro plugin shadows the cairo-lang base inline macro plugin

### ISSUE THREAD

**Issue by LucasLvy** [dojoengine/dojo#731] opened 2023-08-09 18:09 UTC
# Description

When using the `array!` inline macro alongside with `get!` or `set!` inline macros in the same function, the array macro gets dropped by the compiler so there is a compilation error.

# Minimal example

```rs
#[system]
mod spawn {
    use array::ArrayTrait;
    use traits::Into;
    use dojo::world::Context;
    #[derive(Component, SerdeLen, Serde, Drop)]
    struct A {
        #[key]
        val: felt252,
        val2: u8
    }

    fn execute(ctx: Context) {
        let a = array![0];
        set!(ctx.world, A { val: 1, val2: 1 });
        return ();
    }
}
```

compiler errors

```txt
error: Skipped tokens. Expected: statement.
 --> inline_macros:19:1
;
^


error: Skipped tokens. Expected: statement.
 --> spawn:36:1
;
^


error: Skipped tokens. Expected: statement.
 --> spawn:36:1
;
^


error: could not compile `dojo_examples` due to previous error
```

**Comment by tarrencev** [comment] 2023-08-09 18:20
Hmm weird. It should be a noop. Also, the cario-lang inline macro is processed first 🤔

**Comment by wraitii** [comment] 2023-08-14 10:20
I think the original description is incorrect, and it's the Dojo macros that are dropped (well, replaced by nothing, rather).
I think the cause is that https://github.com/starkware-libs/cairo/pull/3818 removed an extra line that drops the code in RC4, if a macro is found somewhere

This whole code was refactored after 2.1, but I think it's still broken in 2.1 itself. See https://github.com/starkware-libs/cairo/pull/3818/files#diff-290095036f2b8ea665fb138b4c9b809b099535bd9cb41ce03edcc6629d83644cL113

So this is actually a cairo bug 😅

**Comment by orizi** [comment] 2023-08-14 13:51
indeed - it seems our `allowing` of down stream macros, accidentally deleted all macros.
the option now is to just switch the order of the plugins - so the dojo plugin would run first.

**Comment by tarrencev** [comment] 2023-08-14 14:11
> indeed - it seems our `allowing` of down stream macros, accidentally deleted all macros. the option now is to just switch the order of the plugins - so the dojo plugin would run first.

This was unfortunately an oversight on my part. I think until next release, it'll be easiest to avoid using the array macro

**Comment by ponderingdemocritus** [comment] 2023-08-22 06:11
@LucasLvy can you confirm fix and close this

**Closed** 2023-08-22 08:47 UTC
Labels: bug
