### ISSUE TITLE
Issue with setting arrays

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#2157] opened 2024-07-07 13:41 UTC
Previous version this worked:

```rust
            set!(
                world,
                (
                    Moves {
                        player, remaining: 100, last_direction: Direction::None(()), can_move: true
                    },
                    Position {
                        player, vec: Vec2 { x: position.vec.x + 10, y: position.vec.y + 10 }
                    },
                    DirectionsAvailable { player, directions: array![Direction::Up], }
                )
            );
```

Now it chucks error of :

```
   dojo_starter::tests::test_world::tests::test_move - Panicked with (0x696e76616c6964207265736f757263652073656c6563746f72 ('invalid resource selector'), 0x454e545259504f494e545f4641494c4544 ('ENTRYPOINT_FAILED'), 0x454e545259504f494e545f4641494c4544 ('ENTRYPOINT_FAILED')).
   ```

If I remove the model from the set, I have no issue.
   
Nothing has changed.

On `1.0.0-alpha.0`.

**Comment by remybar** [comment] 2024-07-12 08:45
Hi @ponderingdemocritus !

I did a test with this model:
```rust
#[derive(Drop, Serde)]
#[dojo::model]
struct DirectionsAvailable {
    #[key]
    player: ContractAddress,
    directions: Array<Direction>,
}
```

and these lines in `actions::spawn()`:
```rust
set!(
    world,
    (
        DirectionsAvailable { player, directions: array![Direction::Up], }
    )
);
```

And I was not able to reproduce this error (on my current branch which is more recent than the `main` branch so I might fix this issue 😅).  Have you more context about this issue ? Because it might be due to previous calls to the  `DirectionsAvailable` model.

**Comment by glihm** [comment] 2024-08-13 17:37
Will close until we have a reproducible example as this may have been fixed with updates.

**Closed by glihm** 2024-08-13 17:37 UTC
Labels: bug, dojo-core
