### ISSUE TITLE
[sozo] add --wait options

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1335] opened 2023-12-27 11:12 UTC
**Is your feature request related to a problem? Please describe.**
When running multiple `sozo auth writer` in a script, using katana with ~5s block time, 
even adding some sleep time between txs it can lead to nonce issues
Waiting for tx to confirm could be convenient especially for testnet/mainnet

**Describe the solution you'd like**

```
 -w, --wait
 Wait for the transaction to confirm
```

**Comment by kariy** [comment] 2023-12-28 03:01
duplicate of #1192

**Closed** 2023-12-28 09:49 UTC
Labels: enhancement, good first issue, sozo
