### ISSUE TITLE
[BUG] Missing Fee Token (STRK) in Katana, Causing Incompatibility with OpenRPC

### ISSUE THREAD

**Issue by Uacias** [dojoengine/dojo#2529] opened 2024-10-13 10:09 UTC
**Describe the bug**
It has come to our attention that the Katana implementation is missing the fee token for STRK. This omission leads to incompatibility with OpenRPC due to the absence of v3 transactions, which rely on the STRK fee token.

**To Reproduce**
1. Invoke the Transfer function:
- Invoke the transfer fn on the STRK fee token contract at the address: `0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d` (default address for STRK token as documented [here](https://docs.starknet.io/tools/important-addresses/)).

2. Attempt to execute any V3 txn

**Expected behavior**
1. STRK token shall be deployed.
2. Transactions shall complete successfully.
3. OpenRPC compatibility.

**Screenshots**

**Additional context**

**Comment by kariy** [comment] 2024-10-13 17:06
hey @Uacias, yup we're aware of this and are working on it (#2524). but im gonna close this issue as they it is a duplicate of #2405

**Closed by kariy** 2024-10-13 17:06 UTC
Labels: bug
