### ISSUE TITLE
[torii] `--events-chunk-size` infinite loop

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1737] opened 2024-03-31 14:50 UTC
**Describe the bug**
On my world, calling torii with `--events-chunk-size` & any value under 7 cause torii to infinite loop call `starknet_getEvents`
Probly introduced with #1688

**Comment by Larkooo** [comment] 2024-04-01 14:14
i cant reproduce this issue. i dont think its associated with #1688 as the PR hasn't been merged yet

**Comment by notV4l** [comment] 2024-04-01 14:17
> i cant reproduce this issue. i dont think its associated with #1688 as the PR hasn't been merged yet

yes glihm noticed me it's not merged yet, i had issue with alpha-10

**Comment by Larkooo** [comment] 2024-04-01 14:23
> > i cant reproduce this issue. i dont think its associated with #1688 as the PR hasn't been merged yet
> 
> yes glihm noticed me it's not merged yet, i had issue with alpha-10

i think it's an issue with the get_events api

**Comment by Larkooo** [comment] 2024-04-01 14:24
for me it happens when i set the --events-chunk-size value to 1. it breaks the get_events api. for now maybe just try to not use that value. does it happen with other values than 1 for you?

**Comment by glihm** [comment] 2024-04-02 13:51
> for me it happens when i set the --events-chunk-size value to 1. it breaks the get_events api. for now maybe just try to not use that value. does it happen with other values than 1 for you?

Will check on lower layers for that to ensure it's something that can be addressed. Thanks for investigating, we don't usually use 1 yes so lower priority than other fixes. :+1:

**Comment by glihm** [comment] 2024-06-19 21:23
iirc it has been changed on Torii. Can be re-open if necessary.

**Closed by glihm** 2024-06-19 21:23 UTC
Labels: bug, torii
