### ISSUE TITLE
After changing the key structure of a model, it's not possible to migrate

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#1936] opened 2024-05-06 20:31 UTC
This might be a limitation in the structure. I don't think this would happen often but it will need to be flagged in the book if it will not be fixed.

![Screenshot 2024-05-07 at 06 15 51](https://github.com/dojoengine/dojo/assets/90423308/53f5a619-ed97-419d-b8de-b5653d8a0c4f)

Reproduce:
1. Migrate a model
2. Change the keys
3. Try migrate again

@kariy

**Comment by jancris100** [comment] 2024-05-07 15:05
Can you assign this to me please? @ponderingdemocritus

**Comment by jancris100** [comment] 2024-05-14 00:52
This issue has someone already assigned ?

**Comment by abdegenius** [comment] 2024-05-23 10:57
Hey, I will love to handle this issue. Can it be assigned to me?!

**Comment by glihm** [comment] 2024-06-10 15:57
@abdegenius @jancris100 sorry for the delay. One of you is up to check if the problem is still present on the latest alpha and try to fix it?

**Comment by abdegenius** [comment] 2024-06-11 13:09
Can this be assigned to me so i can handle it? Thank you.. an any other issue you got please assign them to me

**Comment by glihm** [comment] 2024-06-19 22:33
> Can this be assigned to me so i can handle it? Thank you.. an any other issue you got please assign them to me

Would you please give an idea of how you plan to handle that? Then I'll assign. 👍

**Comment by abdegenius** [comment] 2024-06-22 07:24
I will first check the migrations files and study each relations.. if one table is references to another and data is loaded to the parent it gives rise to this issues.. the way the next structure was added can give raise to this problem as well each key migration should be done as a single so doing a rollback becomes easy. JUST A LOOK THROUGH THE WHOLE CODEBASE CAN GIVE A CLEAR IDEA OF WHAT IS UP

**Comment by glihm** [comment] 2024-06-22 16:25
@abdegenius I think there's more implications here, but please git it a shot and let's know how it goes. If you have any question please don't hesitate here or to reach out on discord.

**Comment by abdegenius** [comment] 2024-06-28 06:50
You are right, can't seem to figure it out! :) still checking tho

**Comment by glihm** [comment] 2024-07-17 22:03
@abdegenius any update on this one?

**Comment by jancris100** [comment] 2024-07-18 00:30
Hi, I'm at it, give me a little more time this week

**Comment by glihm** [comment] 2024-11-11 20:59
Starting with `1.0.0`, models are only upgradeable by adding some fields, and the world double check this is true when upgrading.

Hence, modifying a key is not supported. Only values can be added, we can't modify an existing field or remove one.

**Closed by glihm** 2024-11-11 20:59 UTC
Labels: bug, katana, dojo-lang
